Traceback (most recent call last):
  File "/Users/julienprat/anaconda3/envs/book/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/julienprat/anaconda3/envs/book/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/julienprat/anaconda3/envs/book/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/Users/julienprat/anaconda3/envs/book/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/julienprat/anaconda3/envs/book/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/julienprat/anaconda3/envs/book/lib/python3.10/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/julienprat/anaconda3/envs/book/lib/python3.10/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
class Params(d2l.HyperParameters):
    def __init__(self,
                 alpha = 1.0/3.0,
                 beta = 0.9,
                 delta = 0.1,
                 k_0 = 1.0,
                ):
        self.save_hyperparameters()

------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[1], line 1[0m
[0;32m----> 1[0m [38;5;28;01mclass[39;00m [38;5;21;01mParams[39;00m([43md2l[49m[38;5;241m.[39mHyperParameters):
[1;32m      2[0m     [38;5;28;01mdef[39;00m [38;5;21m__init__[39m([38;5;28mself[39m,
[1;32m      3[0m                  alpha [38;5;241m=[39m [38;5;241m1.0[39m[38;5;241m/[39m[38;5;241m3.0[39m,
[1;32m      4[0m                  beta [38;5;241m=[39m [38;5;241m0.9[39m,
[1;32m      5[0m                  delta [38;5;241m=[39m [38;5;241m0.1[39m,
[1;32m      6[0m                  k_0 [38;5;241m=[39m [38;5;241m1.0[39m,
[1;32m      7[0m                 ):
[1;32m      8[0m         [38;5;28mself[39m[38;5;241m.[39msave_hyperparameters()

[0;31mNameError[0m: name 'd2l' is not defined

